[package]
name = "opusmeta"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22"
mime-sniffer = "0.1.2"
ogg = "0.9"
thiserror = "1"

[lints.clippy.pedantic]
level = "warn"
priority = -1

[lints.clippy]
nursery = "warn"
